server:
  port: 8084
spring:
  application:
    name: paybridge-loan-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://paybridge-postgres:5432/paybridge_loan}
    username: ${SPRING_DATASOURCE_USERNAME:dentamuhajir}
    password: ${SPRING_DATASOURCE_PASSWORD:5MbVqyTEZ42wFS4as9iwZ7}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

product:
  service:
    base-url: http://paybridge-product-svc:8083
    #base-url: http://host.docker.internal:8083
    api-key: f7a3d9e2b1c85a4096e213b764d19a82f35c0e189674bc27d91f4a5e3028c61b

transaction:
  service:
    base-url: http://paybridge-transaction-svc:8082
    api-key: c9d44f1802afef391a0c847fb3bf6967c77a9f0f0ac12c29dfe651eac9442c52

logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG
    reactor.netty.http.client: DEBUG
