server:
  port: 8084

spring:
  application:
    name: paybridge-loan-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: w3c
  otlp:
    tracing:
      endpoint: ${MANAGEMENT_OTLP_TRACING_ENDPOINT:http://paybridge-otel-collector:4318/v1/traces}
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

product:
  service:
    base-url: ${PRODUCT_SERVICE_BASE_URL:http://paybridge-product-svc:8083}
    api-key: ${TOKEN_PRODUCT_SERVICE}

transaction:
  service:
    base-url: ${TRANSACTION_SERVICE_BASE_URL:http://paybridge-transaction-svc:8082}
    api-key: ${TOKEN_TRANSACTION_SERVICE}

logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG
    reactor.netty.http.client: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      transactionService:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
  timelimiter:
    instances:
      productService:
        timeoutDuration: 3s
